name: telemetry-client
appName: telemetry-client
namespace: default
replicas: 1
image: public.ecr.aws/k9o2q4k2/f1_telemetry_client:latest-amd64
imagePullPolicy: Always
containerPort: 20777
protocol: UDP

serviceName: telemetry-client-service
port: 20777
targetPort: 20777
serviceType: LoadBalancer

kafkaTopic: f1_data
bootstrapServers: pkc-e0zxq.eu-west-3.aws.confluent.cloud:9092
saslUsername: N5TMX3PUDJFKEU7X
saslPassword: jRpyQXN6KBtHSOfPSRj40BNGxoYfNn49/GX+eU9kHyXGYP+fyMF7IW/YDFiLKZpU