name: telemetry-client
appName: telemetry-client
namespace: default
replicas: 1
image: public.ecr.aws/k9o2q4k2/f1_telemetry_client:dev15
imagePullPolicy: Always
containerPort: 20777
protocol: UDP

serviceName: telemetry-client-service
port: 20777
targetPort: 20777
serviceType: LoadBalancer

kafkaTopic: f1-data
bootstrapServers: pkc-ymrq7.us-east-2.aws.confluent.cloud:9092
saslUsername: 75WBE7B5DCLWPPCP
saslPassword: UbrDLo7okAZgQhbVPgFF0YkMlo77lb53nDnc6FhzWR/4a9UDx44rCnMdgUyNx54v