---
environments:
  dev:
    values:
      - envs/dev.yaml
---
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: superset
    url: https://apache.github.io/superset
  - name: tidb
    url: https://github.com/pingcap/tidb-operator

helmDefaults:
  wait: true

helmfiles:
  - ./releases/default/telemetry-client/telemetry-client.yaml
  - ./releases/olap/d3-dashboard/d3-dashboard.yaml
  - ./releases/olap/postgresql/postgresql.yaml
  - ./releases/olap/redis/redis.yaml
  - ./releases/olap/superset/superset.yaml
  - ./releases/olap/tidb/tidb.yaml

