apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ required ".Values.name is required" .Values.name }}
  labels:
    app: {{ required ".Values.appName is required" .Values.appName }}
  namespace: {{ required ".Values.namespace is required" .Values.namespace }}
spec:
  replicas: {{ required ".Values.replicas is required" .Values.replicas }}
  selector:
    matchLabels:
      app: {{ required ".Values.appName is required" .Values.appName }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ required ".Values.appName is required" .Values.appName }}
    spec:
      containers:
      - image: {{ required ".Values.image is required" .Values.image }}
        imagePullPolicy: {{ required ".Values.imagePullPolicy is required" .Values.imagePullPolicy }}
        name: {{ required ".Values.name is required" .Values.name }}
        env:
          - name: MYSQL_USER
            value: root
          - name: MYSQL_PASS
            value: NVdtbaf4z5
          - name: MYSQL_HOST
            value: 10.100.171.160
          - name: KAFKA_TOPIC
            value: {{ .Values.kafkaTopic }}
          - name: BOOTSTRAP_SERVERS
            value: {{ .Values.bootstrapServers }}
          - name: SASL_USERNAME
            value: {{ .Values.saslUsername }}
          - name: SASL_PASSWORD
            value: {{ .Values.saslPassword }}
          - name: CLIENT_ID
            value: f1_telemetry_client
        ports:
        - containerPort: {{ required ".Values.containerPort is required" .Values.containerPort }}
          protocol: {{ required ".Values.protocol is required" .Values.protocol }}