apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::241018688765:role/OLAP_workers
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::241018688765:user/szarrinkoub
      username: szarrinkoub
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
