apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "websockets-api.fullname" . }}
  labels:
    {{- include "websockets-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "websockets-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "websockets-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "websockets-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            httpGet:
              path: /api/actuator/health/liveness
              port: 8080
          readinessProbe:
            initialDelaySeconds: 20
            httpGet:
              path: /api/actuator/health/readiness
              port: 8080
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: DRUID_USER
              valueFrom:
                secretKeyRef:
                  name: druid-credentials
                  key: username
            - name: DRUID_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: druid-credentials
                  key: password
            - name: TRUSTSTORE_PASS
              valueFrom:
                secretKeyRef:
                  name: truststore
                  key: password
            {{- range $key, $value := .Values.envVars }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
